# Generated by Django 5.0.12 on 2026-02-13 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='webform', help_text='Source of the lead (e.g., webform, api)', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('page_url', models.URLField(blank=True, default='', help_text='URL of the page where the form was submitted')),
                ('referrer', models.URLField(blank=True, default='', help_text='HTTP referrer URL')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Submitter's IP address", null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text="Submitter's browser user agent")),
                ('first_name', models.CharField(blank=True, default='', max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=80)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('raw_payload', models.JSONField(default=dict, help_text='Complete JSON payload from the form submission')),
                ('status', models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('synced', 'Synced'), ('failed', 'Failed')], db_index=True, default='received', help_text='Current processing status', max_length=20)),
                ('te_contact_id', models.CharField(blank=True, default='', help_text='Total Expert contact ID after sync', max_length=120)),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of sync attempts')),
                ('last_error', models.TextField(blank=True, default='', help_text='Last error message if sync failed')),
                ('queued_at', models.DateTimeField(blank=True, help_text='When this lead was queued to Service Bus', null=True)),
                ('synced_at', models.DateTimeField(blank=True, help_text='When this lead was successfully synced to Total Expert', null=True)),
                ('loan_officer', models.ForeignKey(help_text='The loan officer this lead is assigned to', on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.loanofficer')),
            ],
            options={
                'verbose_name': 'Lead Submission',
                'verbose_name_plural': 'Lead Submissions',
                'db_table': 'lead_submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['-submitted_at'], name='lead_submis_submitt_38c43b_idx'), models.Index(fields=['status'], name='lead_submis_status_b23bd6_idx'), models.Index(fields=['email'], name='lead_submis_email_bfc172_idx'), models.Index(fields=['phone'], name='lead_submis_phone_bfb643_idx')],
            },
        ),
    ]
