# Generated by Django 5.0.14 on 2026-02-10 20:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='webform', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('page_url', models.URLField(blank=True, default='')),
                ('referrer', models.URLField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('first_name', models.CharField(blank=True, default='', max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=80)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('raw_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('synced', 'Synced'), ('failed', 'Failed')], default='received', max_length=20)),
                ('te_contact_id', models.CharField(blank=True, default='', max_length=120)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('loan_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.loanofficer')),
            ],
            options={
                'indexes': [models.Index(fields=['submitted_at'], name='leads_leads_submitt_0870b3_idx'), models.Index(fields=['status'], name='leads_leads_status_40a214_idx'), models.Index(fields=['email'], name='leads_leads_email_c887fc_idx'), models.Index(fields=['phone'], name='leads_leads_phone_a37996_idx')],
            },
        ),
    ]
