# Generated by Django 5.0.12 on 2026-02-13 17:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanOfficer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(db_index=True, max_length=120, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=80)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('te_owner_id', models.CharField(blank=True, default='', help_text='Total Expert owner/user ID', max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this LO is currently accepting leads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan Officer',
                'verbose_name_plural': 'Loan Officers',
                'db_table': 'loan_officers',
                'ordering': ['slug'],
            },
        ),
    ]
