# Generated by Django 5.0.14 on 2026-02-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanOfficer',
        ),
    ]
